name: Multi-Environment Terraform Plan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    # services:
    #   localstack:
    #     image: localstack/localstack
    #     ports:
    #       - 4566:4566
    #     env:
    #       SERVICES: s3
    #       DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize and Plan Dev
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: dev

      - name: Initialize and Plan Dev-Clint
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: dev/clint

      - name: Initialize and Plan Dev-Natasha
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: dev/natasha

      - name: Initialize and Plan Staging-Integration
        if: github.ref == 'refs/heads/master'
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: staging/integration

      - name: Initialize and Plan Staging-Performance
        if: github.ref == 'refs/heads/master'
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: staging/performance

      - name: Initialize and Plan Prod
        if: github.ref == 'refs/heads/master'
        run: |
          terraform init
          terraform plan -var-file="sample-terraform.tfvars" -out=tfplan -input=false -no-color
          terraform show -no-color tfplan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: 'us-east-2'
        working-directory: prod
