name: Terraform

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan -var-file=sample-terraform.tfvars -out=tfplan
        working-directory: terraform/

      - name: Show Terraform Plan
        run: terraform show -json tfplan
        working-directory: terraform/
